project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: https://chenminicode.github.io/
  description: "metseq's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chenminicode
      - icon: rss
        href: index.xml
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

comments:
  giscus:
    repo: chenminicode/chenminicode.github.io
